"""initial

Revision ID: 87c15ac879b5
Revises: 
Create Date: 2025-11-01 14:36:21.651988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '87c15ac879b5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('announcement_groups', 'name',
               existing_type=sa.NVARCHAR(length=250, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               nullable=True)
    op.alter_column('announcement_types', 'name',
               existing_type=sa.NVARCHAR(length=250, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               nullable=False)
    op.alter_column('announcements', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('announcements', 'published_at',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('announcements', 'symbol',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Unicode(length=250),
               existing_nullable=True)
    op.alter_column('announcements', 'has_pdf',
               existing_type=mssql.BIT(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('announcements', 'has_excel',
               existing_type=mssql.BIT(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('announcements', 'has_html',
               existing_type=mssql.BIT(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('announcements', 'is_estimate',
               existing_type=mssql.BIT(),
               server_default=None,
               existing_nullable=True)
    op.create_index(op.f('ix_announcements_id'), 'announcements', ['id'], unique=False)
    op.drop_constraint(op.f('FK__announcem__compa__4AB81AF0'), 'announcements', type_='foreignkey')
    op.add_column('companies', sa.Column('normalized_name', sa.String(length=255), nullable=True))
    op.alter_column('companies', 'name',
               existing_type=sa.NVARCHAR(length=250, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.alter_column('companies', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('companies', 'audited',
               existing_type=mssql.BIT(),
               server_default=None,
               nullable=True)
    op.create_index(op.f('ix_companies_normalized_name'), 'companies', ['normalized_name'], unique=False)
    op.drop_column('companies', 'external_id')
    op.alter_column('industry_groups', 'name',
               existing_type=sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('industry_groups', 'name',
               existing_type=sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.add_column('companies', sa.Column('external_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_companies_normalized_name'), table_name='companies')
    op.alter_column('companies', 'audited',
               existing_type=mssql.BIT(),
               server_default=sa.text('((0))'),
               nullable=False)
    op.alter_column('companies', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(getdate())'),
               existing_nullable=True)
    op.alter_column('companies', 'name',
               existing_type=sa.NVARCHAR(length=250, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.drop_column('companies', 'normalized_name')
    op.drop_constraint(None, 'announcements', type_='foreignkey')
    op.create_foreign_key(op.f('FK__announcem__compa__4AB81AF0'), 'announcements', 'companies', ['company_id'], ['id'])
    op.drop_index(op.f('ix_announcements_id'), table_name='announcements')
    op.alter_column('announcements', 'is_estimate',
               existing_type=mssql.BIT(),
               server_default=sa.text('((0))'),
               existing_nullable=True)
    op.alter_column('announcements', 'has_html',
               existing_type=mssql.BIT(),
               server_default=sa.text('((0))'),
               existing_nullable=True)
    op.alter_column('announcements', 'has_excel',
               existing_type=mssql.BIT(),
               server_default=sa.text('((0))'),
               existing_nullable=True)
    op.alter_column('announcements', 'has_pdf',
               existing_type=mssql.BIT(),
               server_default=sa.text('((0))'),
               existing_nullable=True)
    op.alter_column('announcements', 'symbol',
               existing_type=sa.Unicode(length=250),
               type_=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.alter_column('announcements', 'published_at',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('announcements', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('announcement_types', 'name',
               existing_type=sa.String(),
               type_=sa.NVARCHAR(length=250, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('announcement_groups', 'name',
               existing_type=sa.String(),
               type_=sa.NVARCHAR(length=250, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.create_table('financial_statements',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('announcement_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('content', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], name=op.f('FK__financial__annou__4F7CD00D')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__financia__3213E83FDB01181F'))
    )
    # ### end Alembic commands ###
