label_map = {
    
    "بهاى تمام شده درآمدهای عملیاتی": "cost_of_operating_revenues",
    "درآمدهای عملیاتی": "operating_revenues",
    "سال جاری": "current_year",
    "سال‌های قبل": "previous_years",
    "سایر درآمدها": "other_revenues",
    "سایر درآمدها و هزینه ‏هاى غیرعملیاتى": "non_operating_revenues_and_expenses",
    "سایر هزینه‌ها": "other_expenses",
    "سرمایه": "capital",
    "سود (زیان) خالص عملیات متوقف شده": "net_profit_loss_discontinued_ops",
    "سود (زیان) خالص هر سهم – ریال": "net_profit_loss_per_share_rial",
    "سود(زیان) خالص": "net_profit_loss",
    "سود(زیان) خالص عملیات در حال تداوم": "net_profit_loss_continuing_ops",
    "سود(زیان) عملیات در حال تداوم قبل از مالیات": "profit_loss_continuing_before_tax",
    "سود(زیان) عملیاتى": "operating_profit_loss",
    "سود(زیان) ناخالص": "gross_profit_loss",
    "سود(زیان) پایه هر سهم": "basic_earnings_loss_per_share",
    "سود(زیان) پایه هر سهم:": "basic_earnings_loss_per_share",
    "عملیات در حال تداوم:": "continuing_operations_colon",
    "عملیات متوقف شده:": "discontinued_operations_colon",
    "عملیاتی (ریال)": "operating_rial",
    "غیرعملیاتی (ریال)": "non_operating_rial",
    "ناشی از عملیات در حال تداوم": "from_continuing_operations",
    "ناشی از عملیات متوقف شده": "from_discontinued_operations",
    "هزینه مالیات بر درآمد:": "income_tax_expense",
    "هزینه کاهش ارزش دریافتنی‏ ها (هزینه استثنایی)": "impairment_expense_on_receivables_exceptional",
    "هزینه‏ هاى فروش, ادارى و عمومى": "selling_admin_general_expenses",
    "هزینه‏ هاى مالى": "financial_expenses",
    "جمع درآمدها": "total_revenues",
    "جمع هزینه ها": "total_expenses",
    "درآمدها": "revenues",
    "دوره منتهی به": "period_ended",
    "سود (زیان) تحقق نیافته نگهداری اوراق بهادار": "unrealized_gain_loss_on_securities",
    "سود (زیان) خالص": "net_profit_loss",
    "سود (زیان) فروش اوراق بهادار": "gain_loss_on_sale_of_securities",
    "سود (زیان) قبل از هزینه‌های مالی": "profit_loss_before_financial_expenses",
    "سود اوراق بهادار با درآمد ثابت یا علی‌الحساب": "fixed_income_or_expected_security_profit",
    "سود سهام": "dividend_income",
    "هزینه کارمزد ارکان": "commission_expense_for_entities",
    "هزینه‌ها": "expenses",
    "هزینه‌های مالی": "financial_costs",
        "جمع درآمدهای عملیاتی": "total_operating_revenues",
    "جمع هزینه‌های عملیاتی": "total_operating_expenses",
    "درآمد مالی": "financial_income",
    "درآمد کارمزد و حق‌الزحمه": "commission_and_fee_income",
    "سایر درآمدها و هزینه‏‌هاى غیرعملیاتى": "other_non_operating_income_and_expenses",
    "سود (زیان) سرمایه‌گذاری‌ها": "investment_profit_loss",
    "سود (زیان) عملیاتی": "operating_profit_loss",
    "سود (زیان) قبل از مالیات": "profit_loss_before_tax",
    "هزینه اجاره": "rental_expense",
    "هزینه استهلاک": "depreciation_expense",
    "هزینه مالیات بر درآمد": "income_tax_expense",
    "هزینه‌های حقوق و دستمزد و مزایا": "salary_wages_and_benefits_expense",
    "هزینه‌های عملیاتی": "operating_expenses",
    "تغییرات سایر ذخایر فنی": "changes_in_other_technical_reserves",
    "حق بیمه اتکایی واگذاری": "ceded_reinsurance_premium",
    "حق بیمه خالص (سهم نگهداری)": "net_retained_premium",
    "خسارت سهم بیمه گران اتکایی": "reinsurer_share_of_claims",
    "خسارت و مزایای پرداختی (ناخالص)": "gross_paid_claims_and_benefits",
    "خسارت و مزایای پرداختی خالص": "net_paid_claims_and_benefits",
    "درآمد حق بیمه ناخالص": "gross_premium_income",
        "درآمد سرمایه گذاری از محل منابع بیمه ای": "investment_income_from_insurance_resources",
    "درآمدهای بیمه ای": "insurance_income",
    "سایر درآمدها و هزینه های عملیاتی": "other_operating_income_and_expenses",
    "سایر درآمدها و هزینه های غیر عملیاتی": "other_non_operating_income_and_expenses",
    "سایر درآمدهای بیمه ای": "other_insurance_income",
    "سایر هزینه های بیمه ای": "other_insurance_expenses",
    "سود (زیان) خالص هر سهم– ریال": "net_profit_loss_per_share_rial",
    "سود (زیان) ناخالص فعالیتهای بیمه ای": "gross_profit_loss_from_insurance_activities",
    "سود (زیان) پایه هر سهم": "basic_earnings_loss_per_share",
    "غیر عملیاتی (ریال)": "non_operating_rial",
    "مالیات بر درآمد": "income_tax",
    "هزینه سهم مشارکت در منافع": "participation_share_expense",
    "هزینه های اداری و عمومی": "administrative_and_general_expenses",
    "هزینه های بیمه ای": "insurance_expenses",
    "هزینه های مالی": "financial_expenses",
    "سایر درآمدها و هزینه‌های غیرعملیاتی- اقلام متفرقه": "other_non_operating_misc_items",
    "سایر درآمدها و هزینه‌های غیرعملیاتی- درآمد سرمایه‌گذاری‌ها": "other_non_operating_investment_income",
    "سود (زیان) خالص عملیات در حال تداوم": "net_profit_loss_from_continuing_operations",
    "سود (زیان) عملیات در حال تداوم قبل از مالیات": "profit_loss_continuing_before_tax",
    "سود (زیان) ناخالص": "gross_profit_loss",
    "هزینه کاهش ارزش دریافتنی‌‏ها (هزینه استثنایی)": "impairment_expense_on_receivables_exceptional",
    "هزینه‏‌هاى فروش, ادارى و عمومى": "selling_admin_general_expenses",
    "هزینه‏‌هاى مالى": "financial_expenses",
    "درآمد عملیاتی": "operating_income",
    "زیان خالص": "net_loss",
    "زیان عملیاتی": "operating_loss",
    "زیان ناخالص": "gross_loss",
    "سود خالص": "net_profit",
    "سود عملیاتی": "operating_profit",
    "سود ناخالص": "gross_profit",
    "سود هر سهم": "earnings_per_share",
    "جمع هزینه های عملیاتی": "total_operating_expenses",
    "درآمد سود تضمین شده": "guaranteed_interest_income",
    "درآمد سود سهام": "dividend_income",
    "زیان کاهش ارزش دریافتنی‌ها": "impairment_loss_on_receivables",
    "سود (زیان) تغییر ارزش سرمایه گذاریها": "gain_loss_from_investment_valuation_change",
    "سود (زیان) خالص هر سهم (ریال)": "net_profit_loss_per_share_rial",
    "سود (زیان) عملیاتى": "operating_profit_loss",
    "سود (زیان) فروش سرمایه گذاریها": "gain_loss_on_sale_of_investments",
    "سود (زیان) پایه هر سهم (ریال)": "basic_earnings_loss_per_share_rial",
    "سود (زیان) پایه هر سهم:": "basic_earnings_loss_per_share_colon",
    "هزینه های عملیاتی": "operating_expenses",
    "هزینه ‏هاى حقوق, دستمزد و مزایا": "salaries_wages_benefits_expense"
}
